import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export function registerRepoMap(pi: ExtensionAPI): void {
  pi.registerCommand("repo-map", {
    description: "Build an AST/grep-based symbol index of the repository",
    async handler(args, _ctx) {
      const target = (args ?? "").trim() || ".";
      pi.sendUserMessage([
        `Build a structural map of the codebase at: ${target}`,
        "",
        "## Step 1: Detect Languages",
        "Check for: *.ts, *.js, *.py, *.go, *.rs, *.java, *.rb",
        "",
        "## Step 2: Check for ast-grep",
        "```bash",
        "command -v sg >/dev/null 2>&1 && echo 'AST mode' || echo 'Regex fallback'",
        "```",
        "",
        "## Step 3: Extract Symbols",
        "",
        "### AST mode (if sg available)",
        "Use `sg --pattern` for each detected language to find:",
        "- Exported functions/methods",
        "- Classes, structs, interfaces, types",
        "- Imports (for dependency graph)",
        "",
        "### Regex fallback",
        "Use grep to find exported symbols:",
        "```bash",
        "grep -rnE '^\\s*(export\\s+)?(async\\s+)?function\\s+\\w+' --include='*.ts' | head -200",
        "grep -rnE '^\\s*def\\s+\\w+' --include='*.py' | head -200",
        "grep -rnE '^func\\s+\\w+' --include='*.go' | head -200",
        "```",
        "",
        "## Step 4: Build Dependency Graph",
        "From imports, identify:",
        "- **Entry points** — files with no importers",
        "- **Hubs** — files imported by 5+ others",
        "- **Orphans** — files never imported (possibly dead code)",
        "",
        "## Step 5: Report",
        "```",
        "## Repo Map",
        "",
        "**Languages:** ...",
        "**Files:** N | **Functions:** N | **Classes:** N",
        "",
        "### Entry Points",
        "- src/index.ts (main entry)",
        "",
        "### Hubs (high-impact files)",
        "- src/config.ts — imported by 12 files",
        "",
        "### Orphans (possibly dead code)",
        "- src/legacy/old.ts — never imported",
        "",
        "### Directory Structure",
        "src/",
        "  auth/ — 4 files, 8 exports",
        "  db/ — 3 files, 6 exports",
        "```",
        "",
        "Respect .gitignore. Skip node_modules, dist, binary files, files >100KB.",
        "Cap extraction at 200 results per query.",
      ].join("\n"));
    },
  });
}
